const apiGuideStyles = document.createElement("style");
apiGuideStyles.textContent = `.api-intro{margin:0 0 1rem;color:#60716b;font-size:.8rem}.api-list{display:grid;gap:.7rem}.api-card{padding:1rem;border:1px solid #d7e1dc;border-radius:.6rem;background:#fff}.api-top{display:flex;flex-wrap:wrap;gap:.5rem;align-items:center}.api-card code{color:#064b43;font-size:.82rem;font-weight:800}.api-kind{padding:.18rem .38rem;border-radius:999px;background:#ddf2eb;color:#064b43;font-size:.61rem;font-weight:800}.api-kind.property{background:#fff1ce;color:#795c12}.api-kind.syntax{background:#f2e9ff;color:#704597}.api-card>p{margin:.45rem 0;color:#4f6159;font-size:.77rem}.api-details{display:grid;grid-template-columns:1fr 1fr;gap:.55rem;margin-top:.7rem}.api-detail{padding:.62rem .68rem;border-radius:.38rem;background:#f7faf8;color:#586860;font-size:.7rem}.api-detail b{display:block;margin-bottom:.16rem;color:#285c51;font-size:.66rem}.api-detail code{font-size:.67rem}.api-detail.warning{background:#fff8f5;color:#76574f}.api-detail.warning b{color:#ae5146}.api-example{margin:0;overflow:auto;padding:.68rem;border-radius:.38rem;background:#102a32;color:#d9eae5;font:.68rem/1.65 ui-monospace,monospace;white-space:pre-wrap}@media(max-width:800px){.api-details{grid-template-columns:1fr}}`;
document.head.appendChild(apiGuideStyles);

const apiCatalog = {
  import: { kind: "syntax", name: "import", meaning: "คำสั่งนำ module หรือ library เข้ามาให้เราเรียกใช้ชื่อภายในไฟล์นั้นได้", usage: "import ชื่อ_library as ชื่อย่อ", returns: "ไม่ได้คืนค่าตารางหรือคำตอบ แต่ทำให้ชื่อ library พร้อมใช้", example: "import pandas as pd", warning: "ถ้ายังไม่ได้ติดตั้ง library จะเจอ ModuleNotFoundError" },
  open: { kind: "function", name: "open()", meaning: "function มาตรฐานของ Python สำหรับเปิดไฟล์", usage: "open(path, mode) เช่น open(\"file.csv\", \"r\")", returns: "file object ที่อ่านข้อมูลจากไฟล์ได้", example: "with open(\"data.csv\") as file:\n    text = file.read()", warning: "ใช้ with เพื่อให้ Python ปิดไฟล์ให้ แม้โค้ดด้านในเกิด Error" },
  dictReader: { kind: "function", name: "csv.DictReader()", meaning: "อ่าน CSV แล้วแปลงแต่ละแถวเป็น dictionary โดยใช้แถวแรกเป็นชื่อ key", usage: "csv.DictReader(file_object)", returns: "ตัวอ่านแถว ที่วนด้วย for ได้; แต่ละ row เช่น row[\"name\"]", example: "rows = list(csv.DictReader(file))", warning: "ค่าจาก CSV จะเริ่มเป็นข้อความ จึงต้องแปลง int/float ก่อนคำนวณ" },
  readCsv: { kind: "function", name: "pd.read_csv()", meaning: "function ของ Pandas สำหรับอ่าน CSV เป็น DataFrame", usage: "pd.read_csv(path)", returns: "DataFrame: ตารางที่มีชื่อคอลัมน์และ method สำหรับจัดการข้อมูล", example: "df = pd.read_csv(\"../data/footballers.csv\")", warning: "path อ้างจากโฟลเดอร์ที่กำลังรัน ไม่ใช่จากตำแหน่งที่เราเห็นไฟล์เสมอ" },
  head: { kind: "method", name: "df.head()", meaning: "method คือคำสั่งที่ผูกกับ object; head ดูตัวอย่างแถวแรกของ DataFrame", usage: "df.head() หรือ df.head(n)", returns: "DataFrame ใหม่ที่มี n แถวแรก; ค่าเริ่มต้น n = 5", example: "df.head(3)", warning: "ใช้ดูตัวอย่างเท่านั้น อย่าสรุปจำนวนข้อมูลทั้งหมดจาก head" },
  shape: { kind: "property", name: "df.shape", meaning: "property คือข้อมูลที่ object มีอยู่แล้ว จึงไม่มีวงเล็บ (); shape คือขนาดของตาราง", usage: "df.shape", returns: "tuple เช่น (20, 15): ตัวแรกจำนวนแถว ตัวที่สองจำนวนคอลัมน์", example: "rows, columns = df.shape", warning: "อย่าเขียน df.shape() เพราะ shape ไม่ใช่ method" },
  columns: { kind: "property", name: "df.columns", meaning: "property ที่เก็บชื่อคอลัมน์ทั้งหมดใน DataFrame", usage: "df.columns", returns: "Index ของชื่อคอลัมน์ เช่น name, club, overall", example: "print(df.columns)", warning: "ชื่อคอลัมน์แยกตัวเล็ก-ใหญ่; overall และ Overall ไม่เหมือนกัน" },
  info: { kind: "method", name: "df.info()", meaning: "แสดงสรุปโครงสร้าง DataFrame เพื่อช่วยตรวจชนิดข้อมูลและช่องว่าง", usage: "df.info()", returns: "ปกติพิมพ์รายงานออกหน้าจอและคืน None", example: "df.info()", warning: "ดู non-null count: ถ้าน้อยกว่าจำนวนแถว แปลว่าคอลัมน์นั้นมีค่าหาย" },
  bracket: { kind: "syntax", name: "df[[\"column\"]] / df[\"column\"]", meaning: "วงเล็บเหลี่ยมเป็นการเลือกข้อมูล: ชั้นเดียวเลือกคอลัมน์เดียว, สองชั้นเลือกหลายคอลัมน์เป็นตาราง", usage: "df[\"overall\"] หรือ df[[\"name\", \"overall\"]]", returns: "ชั้นเดียวคืน Series; สองชั้นคืน DataFrame", example: "summary = df[[\"name\", \"club\", \"overall\"]]", warning: "ถ้าต้องส่งหลาย feature ให้ ML ใช้วงเล็บซ้อนเพื่อให้ได้ DataFrame 2 มิติ" },
  rename: { kind: "method", name: ".rename()", meaning: "method สำหรับเปลี่ยน label เช่นชื่อคอลัมน์ โดยปกติไม่แก้ DataFrame เดิม", usage: "df.rename(columns={\"ชื่อเดิม\": \"ชื่อใหม่\"})", returns: "DataFrame ใหม่ที่เปลี่ยนชื่อแล้ว", example: "summary = summary.rename(columns={\"overall\": \"rating\"})", warning: "เก็บผลลัพธ์กลับในตัวแปร มิฉะนั้นชื่อเดิมยังอยู่" },
  copy: { kind: "method", name: ".copy()", meaning: "สร้างสำเนา DataFrame เพื่อแก้ไขต่อโดยแยกจากตัวเดิม", usage: "new_df = df.copy()", returns: "DataFrame ใหม่", example: "clean_df = df.copy()", warning: "ใช้เมื่ออยากยืนยันว่า df ต้นฉบับไม่ถูกแก้ในขั้น clean" },
  isna: { kind: "method", name: ".isna()", meaning: "ตรวจทุกช่องว่าขาดข้อมูลหรือไม่", usage: "df[\"height_cm\"].isna()", returns: "Series ของ True/False; True หมายถึงค่านั้นหาย", example: "df[\"height_cm\"].isna().sum()", warning: "isna ยังไม่ได้บอกจำนวน ต้องตามด้วย sum() หากอยากนับ" },
  sum: { kind: "method", name: ".sum()", meaning: "รวมค่าใน Series; สำหรับ True/False นั้น True มีค่าเท่ากับ 1", usage: "series.sum()", returns: "ตัวเลขรวม", example: "missing_count = df[\"height_cm\"].isna().sum()", warning: "ถ้า Series เป็นตัวเลขจริง sum คือผลรวม ไม่ใช่จำนวนแถว" },
  median: { kind: "method", name: ".median()", meaning: "คำนวณค่ากลางของข้อมูลตัวเลขที่เรียงลำดับ", usage: "series.median()", returns: "ตัวเลขหนึ่งค่า", example: "middle = df[\"height_cm\"].median()", warning: "median เหมาะเมื่อมีค่าที่สูง/ต่ำผิดปกติ แต่ต้องอธิบายเหตุผลก่อนใช้แทน missing" },
  fillna: { kind: "method", name: ".fillna()", meaning: "แทนเฉพาะตำแหน่งที่เป็น missing value", usage: "series.fillna(value)", returns: "Series หรือ DataFrame ใหม่ที่ไม่มีค่า missing ในตำแหน่งนั้น", example: "df[\"height_cm\"].fillna(middle)", warning: "อย่าใช้ 0 เป็นค่าแทนโดยอัตโนมัติ หาก 0 ไม่มีความหมายจริงในข้อมูล" },
  assign: { kind: "method", name: ".assign()", meaning: "สร้าง DataFrame ใหม่พร้อมเพิ่มหรือแทนคอลัมน์ที่ระบุ", usage: "df.assign(column=values)", returns: "DataFrame ใหม่", example: "clean_df = df.assign(height_cm=df[\"height_cm\"].fillna(middle))", warning: "ชื่อทางซ้ายของ = ใน assign คือชื่อคอลัมน์ ไม่ใช่ตัวแปร Python ทั่วไป" },
  ampersand: { kind: "syntax", name: "&", meaning: "operator สำหรับเชื่อมเงื่อนไขแบบ และ เมื่อเงื่อนไขเป็น Series ของ Pandas", usage: "(เงื่อนไขที่ 1) & (เงื่อนไขที่ 2)", returns: "Series ของ True/False ที่จะเป็น True เมื่อผ่านทั้งสองเงื่อนไข", example: "(df[\"age\"] <= 25) & (df[\"overall\"] >= 85)", warning: "ต้องใส่วงเล็บรอบแต่ละเงื่อนไข และอย่าใช้ and กับ Series" },
  query: { kind: "method", name: ".query()", meaning: "กรอง DataFrame ด้วยข้อความเงื่อนไขที่อ่านคล้ายประโยค", usage: "df.query(\"condition\")", returns: "DataFrame ที่เหลือเฉพาะแถวผ่านเงื่อนไข", example: "df.query(\"age <= 25 and overall >= 85\")", warning: "ชื่อคอลัมน์ที่มีช่องว่างหรืออักขระพิเศษต้องครอบด้วย backtick" },
  isin: { kind: "method", name: ".isin()", meaning: "ตรวจว่าค่าแต่ละตัวอยู่ในรายการที่กำหนดหรือไม่", usage: "series.isin([ค่า1, ค่า2])", returns: "Series True/False สำหรับใช้เป็นเงื่อนไขกรอง", example: "df[df[\"league\"].isin([\"La Liga\", \"MLS\"])]", warning: "isin เป็นการเปรียบเทียบหลายค่าพร้อมกัน ไม่ใช่การค้นหาข้อความบางส่วน" },
  groupby: { kind: "method", name: ".groupby()", meaning: "แบ่งตารางออกเป็นกลุ่มตามคอลัมน์ แต่ยังไม่คำนวณคำตอบ", usage: "df.groupby(\"group_column\")[\"value_column\"]", returns: "GroupBy object ที่ต้องตามด้วย mean, count, agg หรือการคำนวณอื่น", example: "df.groupby(\"league\")[\"overall\"]", warning: "groupby อย่างเดียวไม่ใช่ตารางผลลัพธ์ จึงต้องตามด้วย method สรุป" },
  mean: { kind: "method", name: ".mean()", meaning: "หาค่าเฉลี่ยของ Series หรือของแต่ละกลุ่ม", usage: "series.mean() หรือ groupby_result.mean()", returns: "ตัวเลขหนึ่งค่า หรือ Series หนึ่งค่าต่อกลุ่ม", example: "league_mean = by_league.mean()", warning: "ค่าเฉลี่ยไม่บอกจำนวนตัวอย่างหรือความกระจาย ควรดู count ประกอบ" },
  agg: { kind: "method", name: ".agg()", meaning: "สรุปหลายการคำนวณในครั้งเดียว", usage: "grouped.agg([\"count\", \"mean\", \"median\"])", returns: "DataFrame ที่มีผลลัพธ์หลายคอลัมน์", example: "df.groupby(\"league\")[\"overall\"].agg([\"count\", \"mean\"])", warning: "ชื่อ function ใน list ต้องสะกดถูก และค่าบางแบบอาจใช้กับข้อมูลข้อความไม่ได้" },
  sortValues: { kind: "method", name: ".sort_values()", meaning: "เรียงข้อมูลตามค่าใน Series หรือคอลัมน์ใน DataFrame", usage: "series.sort_values(ascending=False)", returns: "Series/DataFrame ใหม่ที่เรียงแล้ว", example: "league_mean.sort_values(ascending=False)", warning: "ค่าเริ่มต้น ascending=True คือเรียงน้อยไปมาก" },
  nlargest: { kind: "method", name: ".nlargest()", meaning: "เลือก n แถวที่มีค่ามากที่สุดของคอลัมน์", usage: "df.nlargest(n, \"column\")", returns: "DataFrame จำนวน n แถวที่เรียงจากมากไปน้อย", example: "top5 = df.nlargest(5, \"overall\")", warning: "ใช้กับคอลัมน์ตัวเลข; ถ้ามี NaN ให้ตรวจคุณภาพข้อมูลก่อน" },
  index: { kind: "property", name: ".index", meaning: "property ที่เก็บ label ของแถวใน Series/DataFrame", usage: "series.index", returns: "Index เช่นชื่อ league หลังจาก groupby", example: "plt.bar(league_mean.index, league_mean.values)", warning: "index ไม่ใช่ method จึงไม่เขียน .index()" },
  values: { kind: "property", name: ".values", meaning: "property ที่ดึงค่าด้านในออกมาเป็น NumPy array", usage: "series.values", returns: "array ของค่าตัวเลขหรือข้อความ", example: "league_mean.values", warning: "หลายกรณีส่ง Series เข้า library ได้ตรง ๆ; ใช้ values เมื่อ library ต้องการ array จริง" },
  pltBar: { kind: "function", name: "plt.bar()", meaning: "function ของ Matplotlib สำหรับสร้างกราฟแท่ง", usage: "plt.bar(x_values, y_values)", returns: "BarContainer ที่แทนแท่งกราฟ", example: "plt.bar(top5[\"name\"], top5[\"overall\"])", warning: "x และ y ต้องยาวเท่ากันและควรมาจากตารางผลลัพธ์เดียวกัน" },
  ylabel: { kind: "function", name: "plt.ylabel()", meaning: "ตั้งข้อความอธิบายแกน Y ของกราฟ", usage: "plt.ylabel(\"ชื่อแกน\")", returns: "Text object", example: "plt.ylabel(\"Average overall\")", warning: "กราฟที่ไม่มีชื่อแกนทำให้คนอ่านไม่รู้ว่าความสูงของแท่งหมายถึงอะไร" },
  show: { kind: "function", name: "plt.show()", meaning: "สั่งให้ Matplotlib แสดงกราฟที่เตรียมไว้", usage: "plt.show()", returns: "ปกติคืน None หลังแสดงภาพ", example: "plt.show()", warning: "ใน Notebook บางครั้งกราฟแสดงเองได้ แต่เขียน show() ช่วยให้ลำดับชัดเจน" },
  resetIndex: { kind: "method", name: ".reset_index()", meaning: "ย้าย index ที่เป็น label กลับมาเป็นคอลัมน์ปกติ", usage: "series.reset_index(name=\"new_name\")", returns: "DataFrame ใหม่", example: "league_mean.reset_index(name=\"average_overall\")", warning: "เหมาะเมื่อจะนำผล groupby ไปทำตารางหรือกราฟต่อ" },
  iloc: { kind: "property", name: ".iloc", meaning: "indexer สำหรับเลือกแถว/คอลัมน์ตามตำแหน่งตัวเลข ไม่ใช่ตามชื่อ", usage: "df.iloc[แถว] หรือ df.iloc[แถว, คอลัมน์]", returns: "Series, DataFrame หรือค่าหนึ่งค่า ตามตำแหน่งที่เลือก", example: "best = result.iloc[0]", warning: "ตำแหน่งเริ่มที่ 0; iloc[0] คือแถวแรกหลังจากที่เราเรียงแล้ว" },
  fstring: { kind: "syntax", name: "f-string", meaning: "รูปแบบข้อความของ Python ที่แทรกค่าตัวแปรใน { } ได้", usage: "f\"ข้อความ {variable:.1f}\"", returns: "string", example: "f\"ค่าเฉลี่ย {best['average_overall']:.1f}\"", warning: "ส่วน :.1f ใช้กับตัวเลข; ถ้าค่าเป็นข้อความจะเกิด Error" },
  trainSplit: { kind: "function", name: "train_test_split()", meaning: "function ของ scikit-learn สำหรับแบ่งข้อมูลเป็นชุดฝึกและชุดทดสอบ", usage: "train_test_split(X, y, test_size=.2, random_state=42)", returns: "4 ส่วน: X_train, X_test, y_train, y_test", example: "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)", warning: "ต้องแบ่ง X และ y พร้อมกันเพื่อให้แถวข้อมูลกับคำตอบยังจับคู่ถูก" },
  fit: { kind: "method", name: ".fit()", meaning: "method ที่สั่งให้ model เรียนรู้จากข้อมูลฝึก", usage: "model.fit(X_train, y_train)", returns: "model ตัวเดิมที่ถูกฝึกแล้ว", example: "model = LinearRegression().fit(X_train, y_train)", warning: "ห้ามใช้ X_test/y_test ในตอน fit เพราะ test ต้องเป็นข้อสอบที่โมเดลไม่เคยเห็น" },
  predict: { kind: "method", name: ".predict()", meaning: "ให้โมเดลที่ฝึกแล้วทำนายคำตอบจาก feature ใหม่", usage: "model.predict(X_test)", returns: "array ของค่าที่โมเดลทำนาย", example: "pred = model.predict(X_test)", warning: "จำนวนคอลัมน์และลำดับ feature ของ X_test ต้องเหมือนตอน fit" },
  mae: { kind: "function", name: "mean_absolute_error()", meaning: "วัดความผิดพลาดเฉลี่ยแบบค่าสัมบูรณ์ หรือ MAE", usage: "mean_absolute_error(y_true, y_pred)", returns: "ตัวเลขความผิดพลาด; ยิ่งต่ำยิ่งดีเมื่อเทียบชุดข้อมูลเดียวกัน", example: "mean_absolute_error(y_test, pred)", warning: "อย่าเทียบค่า MAE ของชุดทดสอบคนละชุดแล้วตัดสินว่าโมเดลใดดีกว่า" },
  valueCounts: { kind: "method", name: ".value_counts()", meaning: "นับความถี่ของค่าที่ไม่ซ้ำกัน", usage: "series.value_counts()", returns: "Series ที่ index คือค่าที่พบ และ value คือจำนวนครั้ง", example: "df[\"position\"].value_counts()", warning: "ค่า missing จะไม่ถูกนับเป็นค่าเริ่มต้น; ใช้ dropna=False หากต้องการเห็นด้วย" },
  describe: { kind: "method", name: ".describe()", meaning: "สรุปสถิติเบื้องต้น เช่น count, mean, min, max", usage: "df.describe()", returns: "DataFrame สรุปสถิติ", example: "df[[\"age\", \"overall\"]].describe()", warning: "describe ไม่บอกสาเหตุของค่าผิดปกติ ต้องกลับไปตรวจแถวดิบ" },
  def: { kind: "syntax", name: "def", meaning: "คำสำคัญสำหรับประกาศ function ของเราเอง", usage: "def ชื่อ_function(parameter):", returns: "สร้าง function object; function จะทำงานเมื่อเรียกชื่อพร้อม ()", example: "def group_average(data, group_col, value_col):\n    return data.groupby(group_col)[value_col].mean()", warning: "เนื้อหาใน function ต้องเยื้อง (indent) และชื่อ parameter ใช้ได้เฉพาะใน function" },
  return: { kind: "syntax", name: "return", meaning: "ส่งค่าจากใน function กลับไปยังจุดที่เรียก function", usage: "return value", returns: "ค่าที่ระบุ และจบการทำงานของ function ตรงนั้น", example: "return result.sort_values(ascending=False)", warning: "print แค่แสดงผล แต่ return ทำให้เอาค่าไปเก็บในตัวแปรหรือใช้ต่อได้" },
  plot: { kind: "property", name: ".plot", meaning: "accessor ของ Pandas ที่เปิดเครื่องมือสร้างกราฟจาก Series/DataFrame", usage: "series.plot.bar()", returns: "PlotAccessor ซึ่งมี method ย่อย เช่น bar(), line(), hist()", example: "result.plot.bar()", warning: "plot เองยังไม่วาดกราฟ จึงต้องตามด้วยชนิดกราฟ เช่น .bar()" },
  plotBar: { kind: "method", name: ".plot.bar()", meaning: "method ของ PlotAccessor สำหรับสร้างกราฟแท่งจาก Pandas", usage: "series.plot.bar(title=\"...\")", returns: "Axes object ของ Matplotlib", example: "result.plot.bar(title=\"Average value by position\")", warning: "ต้องตรวจว่าผลลัพธ์ถูกเรียงและมี label ที่อ่านได้ก่อนวาด" },
  savefig: { kind: "function", name: "plt.savefig()", meaning: "บันทึกกราฟ Matplotlib ที่สร้างแล้วเป็นไฟล์ภาพ", usage: "plt.savefig(\"chart.png\", dpi=150)", returns: "ปกติคืน None และสร้างไฟล์ภาพ", example: "plt.savefig(\"average_value.png\", dpi=150)", warning: "ควรเรียกหลังตั้งชื่อแกน/จัด layout และก่อนปิดหรือเคลียร์รูป" }
};

const guideByWeek = [
  ["import", "open", "dictReader", "readCsv", "head", "shape", "columns", "info"],
  ["bracket", "rename", "copy", "columns"],
  ["isna", "sum", "median", "fillna", "assign"],
  ["ampersand", "query", "isin", "bracket"],
  ["groupby", "mean", "agg", "sortValues"],
  ["nlargest", "index", "values", "pltBar", "ylabel", "show"],
  ["resetIndex", "iloc", "fstring", "sortValues"],
  ["bracket", "trainSplit", "fit", "predict", "mae"],
  ["columns", "valueCounts", "describe", "info", "groupby"],
  ["def", "return", "sortValues", "plot", "plotBar", "savefig"]
];

const weekIndex = Number(document.body.dataset.week) - 1;
const functionsSection = document.querySelector("#functions");
const guide = document.createElement("section");
guide.className = "section";
guide.id = "api-guide";
guide.innerHTML = `<p class="section-label">READ THE CODE, NOT JUST COPY IT</p><h2>Property, method และ function ในบทนี้</h2><p class="api-intro"><b>วิธีแยก:</b> property ไม่มีวงเล็บ เช่น <code>df.shape</code>; method เรียกผ่าน object และมีวงเล็บ เช่น <code>df.head()</code>; function เรียกชื่อโดยตรง เช่น <code>pd.read_csv()</code>. ส่วน syntax คือกฎการเขียนของภาษา Python</p><div class="api-list">${guideByWeek[weekIndex].map(key => {
  const item = apiCatalog[key];
  return `<article class="api-card"><div class="api-top"><code>${item.name}</code><span class="api-kind ${item.kind}">${item.kind}</span></div><p>${item.meaning}</p><div class="api-details"><div class="api-detail"><b>เขียนอย่างไร</b><code>${item.usage}</code></div><div class="api-detail"><b>ได้อะไรกลับมา</b>${item.returns}</div><div class="api-detail warning"><b>ระวัง</b>${item.warning}</div><pre class="api-example"><code>${item.example}</code></pre></div></article>`;
}).join("")}</div>`;
functionsSection.insertAdjacentElement("afterend", guide);

const toc = document.querySelector(".book-toc");
if (toc) toc.insertAdjacentHTML("beforeend", '<a href="#api-guide">คู่มือโค้ด</a>');
