const chapters = [
  {title:"เริ่มต้นและรู้จักข้อมูล", lead:"ก่อนวิเคราะห์ อย่าเพิ่งเชื่อสิ่งที่คิดว่ามีในไฟล์ เราจะเปิดไฟล์ ดูตัวอย่าง และตรวจโครงสร้างให้เป็นก่อน", goals:[["รู้จัก CSV","เข้าใจว่า CSV คือข้อมูลตารางในรูปข้อความ"],["ตรวจโครงสร้าง","ดูแถว คอลัมน์ และชนิดข้อมูลก่อนใช้"],["อ่าน Error","รู้ว่า FileNotFoundError มักหมายถึง path ผิด"],["เลือกเครื่องมือ","เปรียบเทียบ csv มาตรฐานกับ Pandas"]], recap:"นี่คือบทแรก จึงยังไม่มีโค้ดเก่า เราเริ่มจากไฟล์ footballers.csv", prior:"# เริ่มต้นจากไฟล์ข้อมูล\nfootballers.csv", funcs:[["open()","เปิดไฟล์ข้อความด้วย Python ปกติ"],["csv.DictReader()","อ่านแต่ละแถวเป็น dictionary"],["pd.read_csv()","อ่าน CSV เป็นตาราง Pandas"]], normal:"Python ปกติ (csv)", library:"Pandas", pair:[["import csv","import pandas as pd","นำเครื่องมือเข้ามาใช้: csv เป็นมาตรฐาน Python, Pandas เป็น library สำหรับตาราง"],["with open(\"../data/footballers.csv\") as f:\n    rows = list(csv.DictReader(f))","df = pd.read_csv(\"../data/footballers.csv\")","ทั้งคู่เก็บข้อมูลแล้ว แต่ rows คือ list ของ dictionary ส่วน df คือ DataFrame"],["print(rows[:3])","df.head(3)","ดูเพียง 3 แถวก่อน ไม่พ่นทั้งไฟล์ออกมา"]], views:[["มุมมองข้อมูล","ถ้าไม่ตรวจชื่อคอลัมน์ก่อน จะใช้ overall / Overall ผิดและเกิด KeyError"],["มุมมองการเลือกวิธี","ข้อมูลเล็กใช้ csv ได้ แต่ Pandas ทำงานกับตารางและค่าหายได้สะดวกกว่า"]], error:"FileNotFoundError: [Errno 2] No such file or directory", fix:"ตรวจว่ารัน Notebook จากโฟลเดอร์ใด แล้วใช้ path `../data/footballers.csv` จากโฟลเดอร์ challenge/week", challenge:"อ่านไฟล์ แล้วแสดง 3 แถวแรก, จำนวนแถว/คอลัมน์ และอธิบายว่า `shape` สองตัวหมายถึงอะไร"},
  {title:"Data Wrangling",lead:"ข้อมูลมักมีคอลัมน์มากกว่าที่คำถามต้องใช้ บทนี้จัดตารางให้เล็ก ชัด และปลอดภัยต่อการทำงานต่อ",goals:[["เลือกข้อมูล","เก็บเฉพาะคอลัมน์ที่ตอบคำถาม"],["ตั้งชื่อใหม่","ทำรายงานให้ผู้อ่านเข้าใจคำศัพท์"],["ไม่แก้ต้นฉบับ","แยกตารางใหม่ออกจาก df"],["ลดโค้ดซ้ำ","ใช้ Pandas เลือกทั้งคอลัมน์"]],recap:"เราพก df จาก Week 01 มาแล้ว จึงเริ่มจัดรูปข้อมูลได้ทันที",prior:"import pandas as pd\ndf = pd.read_csv(\"../data/footballers.csv\")",funcs:[["dict / loop","สร้างข้อมูลใหม่ทีละแถว"],["df[[...]]","เลือกหลายคอลัมน์เป็นตาราง"],["rename()","เปลี่ยนชื่อคอลัมน์"]],normal:"Python ปกติ (loop)",library:"Pandas",pair:[["summary = []","cols = [\"name\", \"club\", \"overall\"]","ทั้งสองวิธีเริ่มจากบอกว่าจะเก็บข้อมูลอะไร"],["for row in rows:\n    summary.append({\"name\": row[\"name\"], \"club\": row[\"club\"], \"rating\": row[\"overall\"]})","summary = df[cols].rename(columns={\"overall\": \"rating\"})","loop ต้องสร้าง dictionary ทุกแถวเอง; Pandas เลือกและเปลี่ยนชื่อทั้งคอลัมน์"],["print(summary[:3])","summary.head(3)","ตรวจตารางใหม่ก่อนใช้ต่อเสมอ"]],views:[["มุมมองผู้อ่าน","rating อ่านง่ายกว่า overall ในรายงาน แต่ต้องรู้ว่าคือข้อมูลเดียวกัน"],["มุมมองความปลอดภัย","ตารางใหม่ช่วยลดความเสี่ยงที่เราจะเปลี่ยน df ต้นฉบับโดยไม่ตั้งใจ"]],error:"KeyError: 'Overall'",fix:"Python แยกตัวเล็ก-ใหญ่ ตรวจ `df.columns` แล้วใช้ชื่อจริง `overall`",challenge:"สร้าง summary ที่มี name, club, overall และเปลี่ยนชื่อ overall เป็น rating โดย df เดิมต้องไม่เปลี่ยน"},
  {title:"Cleaning data",lead:"ข้อมูลที่หายไม่ใช่สิ่งที่ต้องรีบลบหรือแทนค่า การเลือกวิธี clean ต้องอธิบายได้ว่าเหตุใดจึงเหมาะกับคำถาม",goals:[["หา missing","ตรวจ NaN ก่อนคำนวณ"],["เลือกวิธีแก้","แทนค่า หรือตัดแถวตามเหตุผล"],["ใช้ median","รู้จักค่ากลางที่ทนค่าผิดปกติ"],["เก็บต้นฉบับ","สร้าง clean_df สำหรับงานต่อ"]],recap:"เรามี summary แล้ว แต่การ clean ควรทำกับ df ที่ยังมีข้อมูลจริงครบทุกคอลัมน์",prior:"df = pd.read_csv(\"../data/footballers.csv\")\nsummary = df[[\"name\", \"club\", \"overall\"]]",funcs:[["isna().sum()","นับจำนวนค่าที่หาย"],["median()","หาค่ากลางของตัวเลข"],["fillna()","แทนเฉพาะช่องว่าง"]],normal:"Python ปกติ (if/loop)",library:"Pandas",pair:[["heights = [float(r[\"height_cm\"]) for r in rows if r[\"height_cm\"] != \"\"]","missing = df[\"height_cm\"].isna().sum()","ก่อนแก้ ต้องรู้ว่าหายกี่จุด"],["middle = sorted(heights)[len(heights)//2]","middle = df[\"height_cm\"].median()","ทั้งคู่หาค่ากลาง แต่ Pandas บอกเจตนาชัดและข้าม NaN ให้"],["for row in rows:\n    if row[\"height_cm\"] == \"\": row[\"height_cm\"] = middle","clean_df = df.assign(height_cm=df[\"height_cm\"].fillna(middle))","Pandas สร้างตารางใหม่; ไม่เผลอเปลี่ยนข้อมูลต้นทาง"]],views:[["มุมมองสถิติ","ใส่ 0 แทนส่วนสูงที่หายทำให้ค่าเฉลี่ยเพี้ยน เพราะ 0 ไม่ใช่ส่วนสูงจริง"],["มุมมองธุรกิจ","ถ้าค่าหายมีความหมาย เช่นไม่เปิดเผยข้อมูล อาจไม่ควรแทนค่าเลย"]],error:"TypeError: could not convert string to float: ''",fix:"ตรวจช่องว่างก่อนแปลงตัวเลข หรือให้ Pandas อ่านเป็น NaN แล้วใช้ fillna",challenge:"บทเรียนใช้ height_cm แล้ว — Challenge ให้ใช้ age: นับค่าที่หาย สร้าง clean_df ที่แทน age ด้วย median และอธิบายเหตุผล"},
  {title:"Filter data",lead:"การกรองเปลี่ยนข้อมูลทั้งตารางให้เหลือเฉพาะกลุ่มที่ตอบคำถาม เราจะทำให้เงื่อนไขอ่านง่ายและตรวจสอบได้",goals:[["เขียนเงื่อนไข","ใช้ <=, >= และการเชื่อมเงื่อนไข"],["อ่าน mask","เข้าใจ True/False รายแถว"],["ใช้ query","เขียนกฎที่ยาวให้เหมือนประโยค"],["เลือกคอลัมน์","รายงานเฉพาะสิ่งที่ต้องใช้"]],recap:"clean_df จาก Week 03 ทำให้เราไม่ต้องกังวลข้อมูลส่วนสูงหายเมื่อต้องใช้ต่อ",prior:"clean_df = df.assign(\n    height_cm=df[\"height_cm\"].fillna(df[\"height_cm\"].median())\n)",funcs:[["&","เชื่อมเงื่อนไขแบบ และ"],["query()","กรองด้วยข้อความกฎ"],["isin()","เลือกค่าที่อยู่ในรายการ"]],normal:"Python ปกติ (if/loop)",library:"Pandas",pair:[["future_stars = []","rule = \"age <= 25 and overall >= 85\"","กำหนดเกณฑ์ดาวรุ่งก่อนลงมือกรอง"],["for row in rows:\n    if int(row[\"age\"]) <= 25 and int(row[\"overall\"]) >= 85:\n        future_stars.append(row)","future_stars = clean_df.query(rule)","loop ตรวจทีละคน; query นำกฎไปใช้กับทั้งตาราง"],["print([r[\"name\"] for r in future_stars])","future_stars[[\"name\", \"age\", \"overall\"]]","แสดงเพียงหลักฐานที่ตอบคำถาม"]],views:[["มุมมองตรรกะ","คำว่า และ หมายถึงต้องผ่านทุกเงื่อนไข ไม่ใช่ผ่านข้อใดข้อหนึ่ง"],["มุมมอง Error","Pandas ใช้ `&` กับ Series ไม่ใช้ Python `and` และต้องใส่วงเล็บ"]],error:"ValueError: The truth value of a Series is ambiguous",fix:"เปลี่ยน `and` เป็น `&` และครอบแต่ละเงื่อนไขด้วยวงเล็บ",challenge:"หานักเตะอายุไม่เกิน 25 และ overall ตั้งแต่ 85 แล้วอธิบายว่าทำไมผลมีเพียงบางแถว"},
  {title:"Analysis พื้นฐาน",lead:"การวิเคราะห์เปลี่ยนข้อมูลรายคนเป็นคำตอบภาพรวม แต่ต้องระวังว่าเลขสรุปไม่ได้เล่าเรื่องทั้งหมด",goals:[["แบ่งกลุ่ม","ใช้ league หรือ position เป็นกลุ่ม"],["คำนวณค่าเฉลี่ย","ตอบคำถามภาพรวม"],["เปรียบเทียบ","เรียงผลจากสูงไปต่ำ"],["อ่านข้อจำกัด","ดูจำนวนตัวอย่างร่วมด้วย"]],recap:"future_stars คือผลการกรองหนึ่งกลุ่ม แต่การวิเคราะห์ภาพรวมควรกลับมาดู clean_df ทั้งตาราง",prior:"future_stars = clean_df.query(\"age <= 25 and overall >= 85\")",funcs:[["groupby()","แบ่งข้อมูลเป็นกลุ่ม"],["mean()","หาค่าเฉลี่ย"],["agg()","สรุปหลายค่าในครั้งเดียว"]],normal:"Python ปกติ (dict)",library:"Pandas",pair:[["totals, counts = {}, {}","by_league = clean_df.groupby(\"league\")[\"overall\"]","เตรียมรวมคะแนนแยกลีก"],["for row in rows:\n    league = row[\"league\"]\n    totals[league] = totals.get(league, 0) + int(row[\"overall\"])\n    counts[league] = counts.get(league, 0) + 1","league_mean = by_league.mean()","Pandas เก็บรายละเอียดการรวมและนับไว้ภายใน mean()"],["averages = {k: totals[k]/counts[k] for k in totals}","league_mean.sort_values(ascending=False)","เรียงเพื่ออ่านคำตอบ แต่ต้องดูจำนวนคนในแต่ละลีกประกอบ"]],views:[["มุมมองตัวเลข","ค่าเฉลี่ยสูงไม่ได้แปลว่านักเตะทุกคนในลีกนั้นมีคะแนนสูง"],["มุมมองหลายค่า","ใช้ count, mean, median ร่วมกัน เมื่อไม่อยากเชื่อค่าเฉลี่ยค่าเดียว"]],error:"KeyError: 'leagues'",fix:"ชื่อคอลัมน์จริงคือ `league`; ใช้ `df.columns` ตรวจทุกครั้ง",challenge:"หาค่า overall เฉลี่ยแยกลีก เรียงจากมากไปน้อย แล้วรายงาน count ของแต่ละลีกด้วย"},
  {title:"Visualization",lead:"กราฟช่วยให้เห็นความต่างเร็วขึ้น แต่กราฟที่ไม่มีชื่อแกนหรือเลือกประเภทผิดอาจชวนให้เข้าใจผิดกว่าตาราง",goals:[["เลือกกราฟ","bar chart สำหรับเทียบกลุ่ม"],["เตรียมข้อมูล","ใช้ top5 หรือสรุปกลุ่มก่อนวาด"],["ตั้งชื่อแกน","ให้กราฟอธิบายตัวเอง"],["อ่านกราฟ","แยกสิ่งที่เห็นจากสิ่งที่เดา"]],recap:"league_mean จาก Week 05 คือข้อมูลสรุปที่สะอาดและเหมาะจะนำมาสร้างกราฟ",prior:"league_mean = clean_df.groupby(\"league\")[\"overall\"].mean()\nleague_mean = league_mean.sort_values(ascending=False)",funcs:[["nlargest()","เลือก top n ตามคอลัมน์"],["plt.bar()","สร้างกราฟแท่ง"],["ylabel()","ใส่ความหมายแกน Y"]],normal:"Python ปกติ (ข้อความ)",library:"Matplotlib",pair:[["for name, value in league_mean.items():\n    print(f\"{name}: {'#' * int(value)}\")","import matplotlib.pyplot as plt","ทั้งสองวิธีทำให้เห็นความต่าง; ข้อความเหมาะกับ terminal ส่วน Matplotlib เหมาะกับการสื่อสาร"],["# นับ # เพื่อเทียบความสูง","plt.bar(league_mean.index, league_mean.values)","กราฟแท่งใช้ชื่อและตัวเลขชุดเดียวกัน จึงเปรียบเทียบได้ถูกต้อง"],["# ไม่มีแกนอย่างเป็นทางการ","plt.ylabel(\"Average overall\")\nplt.xticks(rotation=25)\nplt.show()","เพิ่มชื่อแกนและจัดชื่อไม่ให้ทับกัน"]],views:[["มุมมองการสื่อสาร","กราฟไม่ใช่การวิเคราะห์แทนเรา ต้องมีคำอธิบายว่ากำลังเปรียบเทียบอะไร"],["มุมมองคุณภาพ","แกน Y ที่ตัดช่วงอาจทำให้ความต่างดูเกินจริง จึงต้องตรวจ scale"]],error:"ValueError: shape mismatch",fix:"ตรวจให้ข้อมูลแกน X และ Y มาจากตารางเดียวกันและยาวเท่ากัน",challenge:"วาดกราฟแท่ง top 5 overall พร้อมชื่อแกน และเขียน 1 ประโยคว่ากราฟแสดงอะไร"},
  {title:"เล่าเรื่องจากข้อมูล",lead:"ข้อสรุปที่ดีมีคำตอบ หลักฐาน และข้อจำกัด การสื่อสารจึงไม่ใช่การแปะกราฟแล้วปล่อยให้คนดูเดาเอง",goals:[["หาใจความ","เลือกคำตอบหลักหนึ่งข้อ"],["อ้างหลักฐาน","ใช้ตัวเลข/กราฟรองรับ"],["บอกข้อจำกัด","ไม่สรุปเกินข้อมูล"],["ใช้ภาษาเรียบง่าย","ให้คนไม่เขียนโค้ดเข้าใจ"]],recap:"กราฟ Week 06 ให้หลักฐานด้วยภาพ; บทนี้เปลี่ยนหลักฐานนั้นเป็นประโยคที่ตรวจสอบได้",prior:"league_mean.plot.bar()\nplt.ylabel(\"Average overall\")\nplt.show()",funcs:[["round()","ปัดเลขเพื่อสื่อสาร"],["reset_index()","ทำชื่อกลุ่มให้เป็นคอลัมน์"],["f-string","แทรกค่าลงในประโยค"]],normal:"Python ปกติ (format)",library:"Pandas",pair:[["best_name = max(averages, key=averages.get)\nbest_value = averages[best_name]","result = league_mean.reset_index(name=\"average_overall\")","เลือกคำตอบจากผลที่เรียงหรือจาก dictionary"],["message = \"{} is highest at {:.1f}\".format(best_name, best_value)","best = result.iloc[0]","เตรียมข้อมูลเพียงหนึ่งแถวก่อนเล่าเรื่อง"],["print(message + \"; sample sizes may differ.\")","print(f\"ในชุดข้อมูลนี้ {best['league']} มีค่าเฉลี่ย {best['average_overall']:.1f}\")","เติมคำว่าในชุดข้อมูลนี้และข้อจำกัด ไม่เหมารวมเกินหลักฐาน"]],views:[["มุมมองความน่าเชื่อถือ","คำว่า 'ในชุดข้อมูลนี้' บอกขอบเขตได้ดีกว่า 'ลีกนี้ดีที่สุด'"],["มุมมองผู้ฟัง","เริ่มจากคำตอบก่อนค่อยอธิบายวิธีคำนวณ ไม่เริ่มจากโค้ดยาว ๆ"]],error:"ข้อผิดพลาดเชิงเหตุผล: สรุปว่าทุกลีกเป็นแบบเดียวกัน",fix:"ตรวจจำนวนแถวและการคัดเลือกข้อมูล แล้วเขียนข้อจำกัดไว้ในข้อสรุป",challenge:"เขียน 3 ประโยค: สิ่งที่เห็น, หลักฐานจากกราฟ, และสิ่งที่ยังสรุปไม่ได้"},
  {title:"Machine Learning เบื้องต้น",lead:"โมเดลไม่ใช่เวทมนตร์ มันคือกฎที่เรียนรู้ความสัมพันธ์ระหว่างสถิติกับราคา เพื่อนำไปทำนายมูลค่านักเตะชุดใหม่ (Unseen Data)",goals:[["แยก feature/target","รู้ว่าสถิติคือข้อมูลเข้า ($X$) และราคาคือคำตอบ ($y$)"],["แบ่ง train/test","กันข้อมูลไว้ทดสอบความแม่นยำ ป้องกันการจำข้อสอบ"],["วัด MAE","เปรียบเทียบความผิดพลาดของโมเดลกับ Baseline"],["ทำนาย Unseen Data","นำโมเดลไปประเมินราคานักเตะดาวรุ่งชุดใหม่"]],recap:"จาก Week 07 เรารู้ว่าข้อสรุปต้องมีหลักฐาน; ML ก็ต้องมีผลทดสอบและความแม่นยำเป็นหลักฐานเช่นกัน",prior:"# clean_df พร้อมใช้\n# features: overall, age, pace, shooting\n# target: value_millions",funcs:[["train_test_split()","แบ่งชุดฝึกและชุดทดสอบ"],["fit()","ให้โมเดลเรียนรู้จากชุดฝึก"],["predict()","นำโมเดลไปทำนายข้อมูลใหม่"]],normal:"Python ปกติ (baseline)",library:"scikit-learn",pair:[["baseline = sum(y_train) / len(y_train)","from sklearn.linear_model import LinearRegression\nfeatures = [\"overall\", \"age\", \"pace\", \"shooting\"]","baseline คือกฎง่ายที่สุด (ค่าเฉลี่ย) ส่วน scikit-learn มี LinearRegression หาความสัมพันธ์หลายมิติ"],["predictions = [baseline for _ in y_test]","model = LinearRegression().fit(X_train, y_train)\ny_pred = model.predict(X_test)","baseline ทายราคาเท่ากันทุกคน; LinearRegression ประเมินราคาจากสถิตินักเตะ"],["mae = sum(abs(a-p) for a,p in zip(y_test,predictions))/len(y_test)","new_players = pd.read_csv(\"../data/scouted_players.csv\")\nnew_players[\"predicted_value\"] = model.predict(new_players[features]).round(1)","ทั้งสองวัด MAE บน test ได้ และโมเดลยังนำไป predict นักเตะชุดใหม่ที่ไม่เคยเห็นมาก่อนได้ทันที"]],views:[["มุมมองธุรกิจ","โมเดลช่วยแมวมองประเมินราคานักเตะดาวรุ่งจากคุณลักษณะได้รวดเร็ว"],["มุมมองคุณภาพ","ถ้าโมเดลผิดพลาด (MAE) มากกว่า Baseline แปลว่าโมเดลยังใช้งานไม่ได้"]],error:"Expected 2D array, got 1D array instead",fix:"X ต้องเป็นตาราง 2 มิติ เช่น `df_clean[[\"overall\", \"age\", \"pace\", \"shooting\"]]`",challenge:"Clean ข้อมูล value_millions, เทรน LinearRegression, วัด MAE เทียบกับ Baseline และ predict ราคานักเตะใน scouted_players.csv"},
  {title:"Mini project: สำรวจ",lead:"Mini project เริ่มจากคำถามที่ตอบได้ ไม่ใช่เริ่มจากกราฟสวย ๆ เราจะวางขอบเขตและตรวจข้อมูลก่อนเขียนโค้ดจำนวนมาก",goals:[["ตั้งคำถาม","ให้ตอบได้จากคอลัมน์จริง"],["เลือกหลักฐาน","ระบุข้อมูลและกราฟที่จะใช้"],["สำรวจคุณภาพ","หาค่าว่าง/กลุ่มเล็ก"],["วางแผน","ลดการลองผิดลองถูก"]],recap:"Week 08 สอนให้เทียบวิธีอย่างมีหลักฐาน; mini project จึงเลือกวิธีตามคำถาม ไม่ใช่ตามคำสั่งที่จำได้",prior:"# ตัวอย่างคำถาม\nquestion = \"ตำแหน่งใดมีค่าตัวเฉลี่ยสูงสุด?\"\n# clean_df คือข้อมูลที่จัดการ missing แล้ว",funcs:[["columns","ตรวจข้อมูลที่มีจริง"],["value_counts()","ดูจำนวนต่อกลุ่ม"],["describe()","สรุปช่วงของตัวเลข"]],normal:"Python ปกติ (สำรวจ loop)",library:"Pandas",pair:[["positions = {}\nfor row in rows:\n    positions[row[\"position\"]] = positions.get(row[\"position\"], 0) + 1","clean_df[\"position\"].value_counts()","ดูว่ามีกลุ่มใดบ้างและมีตัวอย่างพอเปรียบเทียบหรือไม่"],["values = [float(row[\"value_millions\"]) for row in rows]","clean_df[[\"position\", \"value_millions\"]].info()","ก่อนเฉลี่ย ต้องตรวจชนิดข้อมูลและ missing value"],["# เลือกคำถามหลังอ่านข้อมูล","clean_df.groupby(\"position\")[\"value_millions\"].mean()","การสำรวจพาไปสู่คำถามที่คำนวณได้จริง"]],views:[["มุมมองขอบเขต","คำถามดีระบุทั้งกลุ่มและค่าที่จะวัด เช่น position กับ value_millions"],["มุมมองการออกแบบ","เลือกกราฟหลังรู้ชนิดคำถาม: เปรียบเทียบกลุ่มใช้ bar chart"]],error:"KeyError: 'value_million'",fix:"ชื่อจริงคือ value_millions ตรวจ `df.columns` ก่อนแก้โค้ด",challenge:"เขียนแผน 4 บรรทัด: คำถาม, คอลัมน์, การ clean, กราฟและเหตุผล"},
  {title:"Mini project: นำเสนอ",lead:"บทสุดท้ายทำให้งานของคุณรันซ้ำได้และสื่อสารได้ ผู้เรียนคนอื่นควรเปิด Notebook แล้วเห็นเส้นทางเดียวกับคุณ",goals:[["จัดลำดับ Notebook","อ่านจากบนลงล่างได้"],["ทำซ้ำได้","Restart Kernel แล้ว Run All ผ่าน"],["สื่อสารด้วยกราฟ","มีชื่อและแกนชัด"],["สรุปอย่างรับผิดชอบ","มีคำตอบ หลักฐาน และข้อจำกัด"]],recap:"จาก Week 09 เรามีคำถามและแผนแล้ว บทนี้เปลี่ยนแผนเป็นรายงานที่ผู้อื่นตรวจสอบได้",prior:"question = \"ตำแหน่งใดมีค่าตัวเฉลี่ยสูงสุด?\"\nresult = clean_df.groupby(\"position\")[\"value_millions\"].mean()",funcs:[["def","สร้าง function ใช้ซ้ำ"],["sort_values()","เรียงผลเพื่ออ่านรายงาน"],["savefig()","บันทึกกราฟเป็นภาพ"]],normal:"Python ปกติ (function ของเรา)",library:"Pandas pipeline",pair:[["def average_by_position(rows):\n    # รวมและนับทีละ position\n    ...","result = (clean_df.groupby(\"position\")[\"value_millions\"]\n    .mean().sort_values(ascending=False))","ทั้งสองวิธีทำงานซ้ำได้: function ของเราอธิบายกฎเอง ส่วน pipeline อ่านลำดับการแปลงตาราง"],["report = average_by_position(rows)","result.plot.bar(title=\"Average value by position\")","เมื่อมีผลลัพธ์ ต้องทำให้ผู้อ่านเห็นและตรวจได้"],["print(\"ข้อจำกัด: ข้อมูลมีเพียง 20 แถว\")","plt.ylabel(\"Value (millions)\")\nplt.tight_layout()","ปิดรายงานด้วยข้อจำกัดและกราฟที่มีความหมาย"]],views:[["มุมมองคุณภาพ","Restart Kernel → Run All คือการทดสอบว่าคุณไม่ได้พึ่งตัวแปรที่เคยรันค้างไว้"],["มุมมองการส่งงาน","รายงานที่ดีไม่จำเป็นต้องยาว แต่ทุกผลต้องย้อนกลับไปยังโค้ดและข้อมูลได้"]],error:"NameError: name 'result' is not defined",fix:"สร้าง result ใน cell ก่อนใช้ หรือเรียง cell ใหม่แล้ว Restart Kernel → Run All",challenge:"ส่ง Notebook ที่รันจากบนลงล่างได้ มี 1 กราฟ และสรุปคำตอบ/หลักฐาน/ข้อจำกัด 3 ประโยค"}
];

const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
const week = Number(document.body.dataset.week) - 1;
const chapter = chapters[week];
let visibleSteps = 0;
const app = document.querySelector("#book");

function render() {
  const current = chapter.pair[visibleSteps - 1];
  const normal = visibleSteps ? chapter.pair.slice(0, visibleSteps).map(step => step[0]).join("\n\n") : "# กดปุ่มเพื่อเริ่มดูโค้ดทีละขั้น";
  const library = visibleSteps ? chapter.pair.slice(0, visibleSteps).map(step => step[1]).join("\n\n") : "# กดปุ่มเพื่อเริ่มดูโค้ดทีละขั้น";
  const number = String(week + 1).padStart(2, "0");
  app.innerHTML = `<p class="chapter-kicker">WEEK ${number} · 2 HOURS · CHAPTER</p><h1 class="chapter-title">${chapter.title}</h1><p class="chapter-lede">${chapter.lead}</p><div class="chapter-meta"><span>อ่านเป็นบท</span><span>โค้ดทีละขั้น</span><span>Python เทียบ Library</span></div>
  <section class="section" id="goals"><p class="section-label">WHAT YOU WILL LEARN</p><h2>เมื่อจบบทนี้ คุณจะทำอะไรได้</h2><div class="goals">${chapter.goals.map(goal=>`<article class="goal"><b>${goal[0]}</b>${goal[1]}</article>`).join("")}</div></section>
  <section class="section" id="recap"><p class="section-label">REMEMBER BEFORE YOU CONTINUE</p><h2>ทบทวนโค้ดจากบทก่อน</h2><article class="recap"><h3>โค้ดนี้ยังอยู่กับเราเสมอ</h3><p>${chapter.recap}</p><pre><code>${escapeHtml(chapter.prior)}</code></pre></article></section>
  <section class="section" id="functions"><p class="section-label">FUNCTIONS IN THIS CHAPTER</p><h2>คำสั่งที่ต้องเข้าใจ</h2><div class="function-list">${chapter.funcs.map(f=>`<article class="function-card"><code>${escapeHtml(f[0])}</code><p>${f[1]}</p></article>`).join("")}</div></section>
  <section class="section" id="compare"><p class="section-label">ONE PROBLEM, TWO WAYS</p><h2>เขียนแบบปกติ เทียบกับใช้ Library</h2><p class="compare-intro">สองฝั่งทำโจทย์เดียวกัน จงดูว่าโค้ดปกติต้องจัดการอะไรเอง และ Library ลดงานส่วนใดให้เรา</p><div class="compare"><article class="code-side"><h3>${chapter.normal}</h3><pre class="${visibleSteps?"":"empty"}"><code>${escapeHtml(normal)}</code></pre></article><article class="code-side library"><h3>${chapter.library}</h3><pre class="${visibleSteps?"":"empty"}"><code>${escapeHtml(library)}</code></pre></article></div><div class="step-note"><b>${current?`ขั้นที่ ${visibleSteps}:`:"ก่อนเริ่ม:"}</b> ${current?current[2]:"เมื่อกดปุ่ม โค้ดทั้งสองฝั่งจะเพิ่มทีละขั้นพร้อมกัน"}</div><div class="actions"><button class="next" id="next" ${visibleSteps===chapter.pair.length?"disabled":""}>${visibleSteps===chapter.pair.length?"ครบทุกขั้นแล้ว ✓":visibleSteps?"แสดงขั้นถัดไป →":"แสดงขั้นแรก →"}</button><button class="reset" id="reset">เริ่มส่วนเปรียบเทียบใหม่</button></div></section>
  <section class="section" id="perspectives"><p class="section-label">THINK FROM MORE THAN ONE ANGLE</p><h2>มุมที่ต้องคิดเพิ่ม</h2><div class="perspectives">${chapter.views.map((view,i)=>`<article class="perspective ${i?"warn":""}"><h3>${view[0]}</h3><p>${view[1]}</p></article>`).join("")}</div></section>
  <section class="section" id="error"><p class="section-label">READ THE ERROR</p><h2>จุดที่มักพัง</h2><article class="error-box"><code>${escapeHtml(chapter.error)}</code><p><b>วิธีคิดก่อนแก้:</b> ${chapter.fix}</p></article></section>
  <section class="section challenge" id="challenge"><p class="section-label">PRACTICE</p><h2>Challenge ของ Week นี้</h2><p>${chapter.challenge}</p><ol><li>รันโค้ดแล้วดูผลหรือ Error ก่อน</li><li>เขียนคำตอบด้วยตัวเอง</li><li>ตรวจว่ารันจากบนลงล่างได้</li></ol><a href="../../challenge/challenge_${week+1}.ipynb">เปิดไฟล์ Challenge ของ Week ${number}</a></section>
  <nav class="chapter-nav">${week?`<a href="week-${String(week).padStart(2,"0")}.html">← Week ${String(week).padStart(2,"0")}</a>`:""}${week<chapters.length-1?`<a href="week-${String(week+2).padStart(2,"0")}.html">Week ${String(week+2).padStart(2,"0")} →</a>`:""}</nav>`;
  document.querySelector("#next").addEventListener("click",()=>{visibleSteps+=1;render()});
  document.querySelector("#reset").addEventListener("click",()=>{visibleSteps=0;render()});
}
render();
const apiGuideScript = document.createElement("script");
apiGuideScript.src = "../api-guide.js";
document.body.appendChild(apiGuideScript);
